version: '3'

services:
  db:
    container_name: postgres
    image: postgres:13.1
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - cookbook:/var/lib/postgresql/data

volumes: 
  cookbook:
